### ISSUE TITLE
pnpm安装后yarn dev报错

### ISSUE THREAD

**Issue by qidasheng369** [ArcherGu/vite-react-nestjs-electron#167]
`
yarn run dev
error This project's package.json defines "packageManager": "yarn@pnpm@9.11.0". However the current global version of Yarn is 1.22.22.

Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.
`

**Comment by ArcherGu** [comment]
你用pnpm dev呢

**Comment by qidasheng369** [comment]
> 你用pnpm dev呢

用pnpm run dev是可以的。

**Comment by ArcherGu** [comment]
恩，因为我在package.json里指定了包管理器，yarn应该会检测这个字段，发现不是自己就报错了
